### ISSUE TITLE
Cannot open file nimpy

### ISSUE THREAD

**Issue by gbettle** [joenano/liveodds#1]
Hi Joe,

Many thanks for the repo - hope I can get it working.

I've downloaded all requirements and nim is installed.

C:\Users\garry\Downloads\liveodds>python example.py
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from lib.liveodds import Liveodds
  File "C:\Users\garry\Downloads\liveodds\lib\liveodds.py", line 4, in <module>
    import lib.odds as odds
ModuleNotFoundError: No module named 'lib.odds'

C:\Users\garry\Downloads\liveodds>build.bat

C:\Users\garry\Downloads\liveodds>nim c --gc: orc --threads:on --app:lib --tlsEmulation:off -d:ssl -d:release --out:lib/odds.pyd src/odds.nim
Hint: used config file 'C:\Users\garry\Downloads\nim-1.6.2_x64\nim-1.6.2\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\garry\Downloads\nim-1.6.2_x64\nim-1.6.2\config\config.nims' [Conf]
......................................................................................................................................
C:\Users\garry\Downloads\liveodds\src\odds.nim(4, 8) Error: cannot open file: nimpy
C:\Users\garry\Downloads\liveodds>pip install nimpy
ERROR: Could not find a version that satisfies the requirement nimpy (from versions: none)
ERROR: No matching distribution found for nimpy

C:\Users\garry\Downloads\liveodds>tree /f
Folder PATH listing
Volume serial number is A627-C555
C:.
│   build.bat
│   build.sh
│   example.py
│   README.md
│   requirements.txt
│
├───docs
│       liveodds.html
│
├───lib
│   │   liveodds.py
│   │   odds.so
│   │
│   └───__pycache__
│           liveodds.cpython-38.pyc
│
└───src
    │   odds.nim
    │
    └───utils
            bookies.nim
            xmlfuncs.nim

**Comment by joenano** [comment]
I havent got round to testing this on windows yet so could be missing something.

Did you pip install nimporter? Says on their page that it handles nimpy by default. You could try installing nimpy with nimble(Nim package manager).

```
nimble install nimpy
```

**Comment by joenano** [comment]
I should probably redo this in pure python to be honest, I only used nim for learning, its not necessary.
